on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
name: CI
jobs:
  flatpak:
    permissions:
      actions: write
      
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: AnythingLLM.flatpak
          manifest-path: flatpak.yaml
          cache-key: flatpak-builder-${{ github.sha }}
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: flatpak-bundle
          path: "*.flatpak"

  release:
    permissions:
      contents: write

    needs: flatpak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: flatpak-bundle
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          files: |
            *.flatpak
            */*.flatpak
