on:
  push:
    tags: ["*"]
  pull_request:
name: Flatpak Build
jobs:
  flatpak:
    permissions:
      contents: write

    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: AnythingLLM.flatpak
          manifest-path: flatpak.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false
      - name: Display built files
        run: ls -R
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: |
            *.flatpak
            */*.flatpak
